### PR TITLE
Fixed color link + text-brand

### PR DESCRIPTION
**Pull request by israelperezglez**
@noelmarkham could you review this PR please?
- We fixed text brand in home page
- We fixed text brand in doc page
- We change color links

### CODE REVIEW

**Comment by noelmarkham** [comment]
@israelperezglez I think you've concatenated the style on to one line - would you be able to fix that?

Also, will this have an effect on the other sites that depend on this CSS?

**Comment by israelperezglez** [comment]
@noelmarkham I updated the style file. Yes, we add a new property with "white-space". This property is for keeping all text in one line. This change is good for the others microsites.

**Comment by noelmarkham** [comment]
This LGTM, even though CSS isn't my strongest thing. As long as we're sure this will be fine across the other sites, then I'm happy.

**Comment by rafaparadela** [comment]
LGTM

**Pull request merged**
